version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    container_name: my-postgres-nest-test
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
